added new change

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -13,14 +13,16 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v3
 
-    - name: Deploy to Ec2
+    - name: Execute remote SSH commands using SSH key
       uses: appleboy/ssh-action@v1
       with:
         host: ${{ secrets.EC2_HOST }}
         username: ${{ secrets.EC2_USER }}
         key: ${{ secrets.EC2_SSH_KEY }}
         script: |
-          # Install git if missing
+          set -e  # Exit on error
+          
+          # Ensure git is available
           if ! command -v git &> /dev/null; then
             sudo apt update && sudo apt install -y git
           fi
@@ -35,15 +37,48 @@ jobs:
           else
             echo "Cloning fresh..."
             sudo find /var/www/html -mindepth 1 -delete
-            git clone https://github.com/infrababa/tour-site.git .
+            git clone git@github.com:infrababa/tour-site.git .
           fi
 
-          # Set proper permissions for nginx
+          # Permissions
           sudo chown -R www-data:www-data /var/www/html
           sudo chmod -R 755 /var/www/html
 
-          # Reload nginx
           sudo nginx -t && sudo systemctl reload nginx
-          
           echo "Deployment completed!"
+
+
+    # - name: Deploy to Ec2
+    #   uses: appleboy/ssh-action@v1
+    #   with:
+    #     host: ${{ secrets.EC2_HOST }}
+    #     username: ${{ secrets.EC2_USER }}
+    #     key: ${{ secrets.EC2_SSH_KEY }}
+    #     script: |
+    #       # Install git if missing
+    #       if ! command -v git &> /dev/null; then
+    #         sudo apt update && sudo apt install -y git
+    #       fi
+
+    #       # Prepare directory
+    #       cd /var/www/html
+    #       sudo chown -R $USER:$USER /var/www/html
+
+    #       if [ -d ".git" ]; then
+    #         echo "Repo exists, pulling latest..."
+    #         git pull origin main
+    #       else
+    #         echo "Cloning fresh..."
+    #         sudo find /var/www/html -mindepth 1 -delete
+    #         git clone https://github.com/infrababa/tour-site.git .
+    #       fi
+
+    #       # Set proper permissions for nginx
+    #       sudo chown -R www-data:www-data /var/www/html
+    #       sudo chmod -R 755 /var/www/html
+
+    #       # Reload nginx
+    #       sudo nginx -t && sudo systemctl reload nginx
+          
+    #       echo "Deployment completed!"
 
